- .github/linters/.openapirc.yml
- .github/workflows/linter.yml
- Makefile
Aims to close #3 by adding relevant Github Action.
Uses spectral OAS linter via https://github.com/github/super-linter 
Sample output (with some manually created errors):
```
Linting [OPENAPI] files...
----------------------------------------------
----------------------------------------------
---------------------------
File:[/github/workspace/ipfs-pinning-service.yaml]
ERROR! Found errors in [spectral] linter!
ERROR:[OpenAPI 3.x detected
/github/workspace/ipfs-pinning-service.yaml
1:1   warning  openapi-tags                   OpenAPI object should have non-empty `tags` array.
2:6   warning  info-contact                   Info object should contain `contact` object.
33:9   warning  operation-operationId          Operation should have an `operationId`.
36:11  warning …
```
> feat: validate OpenAPI YAML

- README.md
- docs/index.html
This PR adds human-readable docs for YAML in `master` 
Closes #4
(Merging as-is to make things easier to review, we can improve this in separate PRs)
> docs: human-readable spec with RapiDoc

- ipfs-pinning-service.yaml
This version is  following spec drafted during Pinning Summit where we switched API to operate on "pin objects" with some improvements based on initial feedback and discussions received from the community this week.
This is by no means the finished spec: goal is to close some topics and kick-off discussions on remaining items.
:question: – needs clarification or further discussion
⁉️– potentially controversial
(for now those are just strings)
It can represent direct (`0`) and recursive (`-1`) pins just fine, but opens more advanced strategies in the future. 
- <del> ⁉️ `GET /pins/?cid=Qm&depth=1` could return pin status of arbitrary subtree</del> `depth` is just a simple filter (direct/recursive)
Docs for `feat/pinning-summit-variant-v0.0.2` branch can be viewed at:
- …
> v0.0.2: Pinning Summit + initial feedback

- ipfs-pinning-service.yaml
This PR 
- <del>moves `depth` from being a mandatory field to optional `meta` attributes. 
(as per feedback in https://github.com/ipfs/pinning-services-api-spec/pull/16)</del> Removed as per https://github.com/ipfs/pinning-services-api-spec/pull/19#discussion_r453685376
- documents various uses of `meta` fields, including peering hints to speed up transfer of data that is not already on the pinning service (closes #18, as per feedback in https://github.com/ipfs/pinning-services-api-spec/issues/18#issuecomment-656778692)
cc @obo20 @achingbrain
> Remove Pin.depth and add meta examples

- ipfs-pinning-service.yaml
This PR 
- adds `PinResults`  object
- `PinResults.count` indicates the size of total number of results for pagination
(closes #12 as per feedback in https://github.com/ipfs/pinning-services-api-spec/issues/12#issuecomment-656425010)
-  Makes it easier to set hard limits on the number of responses for a single query
- adds explicit limits on filter results (`cid` and `status`), as per feedback in https://github.com/ipfs/pinning-services-api-spec/issues/15#issuecomment-656742892 and closes #15
**Docs preview for this PR:** https://bafybeid6e52x5oyeeefa27r3yszp7r64j6i4tekznjkoqvc4tw3qh3sxry.ipfs.dweb.link/
----
@obo20 this change adds hard limit to all arrays (params and in `/pins` request/response):
```
maxItems: 1000
```
Let us know if this is ok or should be adjusted (we'd like to keep …
> Limit size of param and request/response arrays

- docs/index.html
Adding inline code to the API docs' introductory material revealed an additional inconsistency with IPFS docs: should be charcoal, not that weird brown-red.
> Make inline code color in intro material consistent with IPFS docs

- ipfs-pinning-service.yaml
This PR adds `Pin.providers` and `PinStatus.providers` as lists of max 20 multiaddrs. 
- `Pin.providers` is now optional and can be empty
- `PinStatus.providers` is now mandatory and needs to  have at least one multiaddr 
The goal is to encourage pinning services to provide own multiaddrs in pin response under  `PinStatus.providers` to ensure clients behind restrictive NAT can dial back and reach pinning service to facilitate data transfer.
As per
https://github.com/ipfs/pinning-services-api-spec/issues/22#issuecomment-657788004
https://github.com/ipfs/pinning-services-api-spec/issues/22#issuecomment-657793428
Closes #22 cc @obo20
> Make providers a required field

- ipfs-pinning-service.yaml
Addressing feedback from https://github.com/ipfs/pinning-services-api-spec/issues/23#issuecomment-657918998 regarding performance constraints:
- merge `resolving` and `retrieving` states into single `pinning`
- remove array support from `status` filter
- spec that no filter request to `GET /pins` return only `pinned` items
Closes #23 cc @obo20
> Simplify status filter

- ipfs-pinning-service.yaml
As discussed out-of-band, copy edits throughout for consistency of language and capitalization. 
Also rewrote introductory section as explicit HTML (escaping out double quotes as needed) so markdown formatting cues didn't get interpreted as random bits of YAML.
> Copy edits for consistency

- ipfs-pinning-service.yaml
This PR removes `unpinned` from `Status` enum.
There is no way to end up in "unpinned" state when using this API other than removing a pin object. 
This implies pinning service is required to keep a history of all past pins in case user wants to bring them back. 
After internal reviews this status does not make sense for MVP, is not useful for integration with IPFS Desktop/WebUI
If user wants to bring back old Pin (eg. due to its metadata), they can read it before unpinning, persist it off-band and then add a new Pin in the future.
cc @obo20
> Remove unpinned status

- ipfs-pinning-service.yaml
This adds `queued` status for indicating scheduled pinning operations that did not start yet.
It is based on feedback from IPFS Cluster (cc @lanzafame) which suggested we should make it very clear when pinning is actively happening, and when it is pending due to service load etc. People coming to distributed systems should have better insight into what is happening, and where the delay comes from.
Because this introduces second "pinning-in-progress" status,
we restore `status` parameter to accept multiple states.
cc @obo20 for visibility, as this partially reverts #28 and brings filtering over multiple states back
> Add queued status, restore status array filter

- ipfs-pinning-service.yaml
This PR enables filtering by free-form metadata attached to `Pin` object.
It makes it possible for apps to attach arbitrary tags to `Pin` and then ask Pinning Service only for tagged pins.
Without this, apps have to fetch all Pins and filter them out locally.
Assuming we want to find `Pin` objects created with  `Pin.meta[foo] = "bar"`, the query would be `GET /pins?meta={"foo":"bar"}`
cc @obo20 this is a simplified version of your `metadata[keyvalues]` filter
> Add metadata filter and examples

- docs/index.html
Adds style attributes to override ReDoc defaults.
Preview: https://gateway.ipfs.io/ipfs/QmQo7UkbAR7oJpRGQ9XSUP9tz4ftVUvASQ2uLn4sCFKP5X
Note: We could use the (undocumented) `theme.ts` to do this if we self-hosted ReDoc (see https://github.com/Redocly/redoc#redoc-options-object), but for folks building on a CDN version, overriding in this manner seems to be the standard approach (https://github.com/Redocly/redoc/issues/827).
> Add style overrides

- ipfs-pinning-service.yaml
This PR aims to address feedback about nondeterministic pagination, and inability to list pins created in specific time range:
- adds `PinStatus.created` timestamp which indicates when a pin request was registered at pinning service (queued)
- note: this is an immutable (write-once) value, it never changes
- removes `skip` parameter from `GET /pins`
- adds `before` and `after` filters to enable time-based pagination over items in deterministic way
- this is also faster than the old offset based mode, because less data needs to be read to produce a batch
**DOCS PREVIEW**: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/feat/created-timestamp/ipfs-pinning-service.yaml
Closes #38 cc #12 @obo20 @GregTheGreek @priom …
> Add PinStatus.created and time-based pagination

- docs/index.html
- ipfs-pinning-service.yaml
This simplifies authorization logic and removes the surface for leaking token via URL as noted in https://github.com/ipfs/pinning-services-api-spec/issues/37#issue-665397179
Pinning Services only need to implement support for the HTTP header.
PREVIEW: https://bafybeib4xyzuzrsk5pl5vvqt6mwlor2w2xj6b6yqj7lgqrlhoafgmgaoey.ipfs.dweb.link/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/remove-auth-parameter/ipfs-pinning-service.yaml
Closes #37 cc @obo20 @GregTheGreek @priom @jsign  @sanderpick @andrewxhill
> Simplify access token spec

- README.md
- ipfs-pinning-service.yaml
This PR adds the context diagram suggested by Pooja as the very first thing in the README.
Preview: 
- https://github.com/ipfs/pinning-services-api-spec/blob/docs/context-diagram/README.md#pinning-service-api-spec
Ref. https://www.figma.com/file/nTnNpsj68kT1dI7WXyQ2QS/Pinning-Service-Core
cc @pooja @eshon @jessicaschilling
> Add context diagram

- ipfs-pinning-service.yaml
This PR removes arrays and replaces them with single object in places which were missed before when we made the switch to single ops – context: https://github.com/ipfs/pinning-services-api-spec/pull/39#issuecomment-665274030
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/fix/single-pin-ops-everywhere/ipfs-pinning-service.yaml
Closes #46 cc @obo20
> fix: single pin I/O in POST operations

- ipfs-pinning-service.yaml
This PR  does not change the spec, it simplifies docs related to `/pins` endpoint
- `/pins/{cid-of-pin-object}` can be confusing because we mean `PinStatus.id`, but a field named `cid` is present in `PinStatus.Pin.cid`
- `/pins/{id}` has a clear connection to `PinStatus.id` and reduces cognitive overhead
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/docs/clarify-object-id/ipfs-pinning-service.yaml
> docs: clarify use of PinStatus.id

- ipfs-pinning-service.yaml
This renames `PinStatus.meta` to `PinStatus.info`
Together with #50   Closes https://github.com/ipfs/pinning-services-api-spec/issues/41
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/disambiguating-meta/ipfs-pinning-service.yaml
> fix: disambiguating *.meta fields

- ipfs-pinning-service.yaml
Renaming according to poll results:
Closes #41
> fix: disambiguating *.providers fields

- ipfs-pinning-service.yaml
This PR is a preparation for v0.0.5 (updating docs, diagrams, fixing typos)
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/cleanup-before-v0.0.5/ipfs-pinning-service.yaml
> chore: v0.0.5

- ipfs-pinning-service.yaml
This PR fixes examples generated from YAML. 
Docs now include inlined examples of how arrays should be passed in each query param:
> ![2020-08-26--17-20-51](https://user-images.githubusercontent.com/157609/91323130-d4e90700-e7c0-11ea-930e-cd8ecb2aecfb.png)
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/docs/query-param-examples/ipfs-pinning-service.yaml
Closes #54 cc @andrew @obo20
> docs: query params examples

- README.md
This PR updates the _Adoption_ section in README to list client/server implementations made by @andrew and @aschmahmann
> docs(readme): update adoption section

- ipfs-pinning-service.yaml
This PR updates description of `name` filter and removes ambiguity, as noted in https://github.com/ipfs/pinning-services-api-spec/issues/45#issuecomment-682608214 by @andrew and @obo20 
The rationale for going with case-sensitive is that it is more performance out of the box, does not require any additional indexes or optimizations, and one can use third-party case-sensitive identifiers (other than CID).
Case-insensitive makes it easier to search and returns not false-negatives, but comes with a risk for bugs when a search results in table scan even when there is an index on the name column.
Let's review which way to go in this PR.
**Update:** we went with case-insensitive
> docs: case-insensitive Pin.name filter

- ipfs-pinning-service.yaml
This PR updates docs and renames "modify" operation with "replace":
- "update" and "modify" do not describe what is actually happening.
- "replace" should make it easier to reason about the purpose of this operation.
Preview: https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/docs/replace-call/ipfs-pinning-service.yaml
> docs: clarify replace operation

- ipfs-pinning-service.yaml
This PR sets limit of 10 CIDs passed via `cid` filter to the `GET /pins` endpoint as suggested in #53
Closes #53 cc @obo20 @jacobheun
> fix: adjust cid filter limits

- ipfs-pinning-service.yaml
This PR:
-  removes reliance on HTTP semantics for error codes and switches to a generic `HTTP 400` with `Error` object in body that is returned with mandatory `reason` string and optional `details`, as proposed in https://github.com/ipfs/pinning-services-api-spec/issues/57
- Every endpoint now has only two response types: _success_ and _error_, and success has the name of returned object in its description, making the spec docs easier to read:
**PREVIEW:** https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/feat/error-codes/ipfs-pinning-service.yaml
Closes #57 @obo20 @andrew  @GregTheGreek @priom @jsign  @sanderpick @andrewxhill @ipfs/wg-pinning-services 
Please provide feedback (even if its just :+1: / :-1:)
> feat: improved error responses

- ipfs-pinning-service.yaml
This is an attempt to clarify the difference between `cid` identifier in request and `id` in response:
- adds "Identifiers" section to the docs and clarifies purpose of each
- **BREAKING CHANGE:** `id` is renamed to `requestid`
- I believe this will make it easier for people to reason `requestid` vs `cid`, but can restore old field name if community decides it is not worth the hassle.
**PREVIEW:** https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/docs/pid/ipfs-pinning-service.yaml
cc @obo20 @andrew @aschmahmann  @GregTheGreek @priom @jsign  @sanderpick @andrewxhill @ipfs/wg-pinning-services 
Please provide feedback (even if its just :+1: / :-1:)
> refactor: rename PinStatus id → requestid

- ipfs-pinning-service.yaml
This PR renames `Error` response object to `Failure`
The idea is to avoid ambiguous `ErrorError` in generated client code.
This does not change the JSON format sent between client and server.
cc @aschmahmann @andrew
> style: rename object returned with error

- ipfs-pinning-service.yaml
This PR changes the default behavior of the `name` filter 
from **case-insensitive, partial match** 
to much faster **case-sensitive, exact (full)  match**
and adds `match` parameter that enables opt-in into alternative strategy when performance is not an object:
> ![Screenshot_2020-10-26 IPFS Pinning Service API](https://user-images.githubusercontent.com/157609/97210699-4132b780-17be-11eb-809a-5747fcda0244.png)
**PREVIEW:** https://ipfs.github.io/pinning-services-api-spec/#specUrl=https://raw.githubusercontent.com/ipfs/pinning-services-api-spec/fix/default-to-fast-name-match/ipfs-pinning-service.yaml
- **Case-insensitive partial "Fuzzy" search (`ipartial`) makes a bad default. (performance-wise)** 
Database indexes and b-trees do not solve the performance fully.
Exact match is always …
> feat: fast exact name search by default

- .gitignore
- ipfs-pinning-service.yaml
This PR updates docs and examples related to `origins` and `delegates` multiaddr arrays:
- makes it explicit that connection dials to origins and delegates are   best-effort, and should not fail the pinning
- swaps examples to use fully resolved multiaddrs, that can immediately  be acted upon (IPs from test ranges  defined in [rfc5737](https://tools.ietf.org/html/rfc5737))
Thanks to @obo20 for raising the ambiguity here – lmk if this clears things out.
> docs: clarify use of provider hints

- README.md
- ipfs-pinning-service.yaml
This PR does not change the spec, only clarifies docs about meta encoding when used for filtering + cleans up some intro text.
- The goal here is to specify how `meta`  should be encoded so we can unblock  https://github.com/ipfs/go-pinning-service-http-client/issues/8 
- We only had to update docs because we are already use the [suggested YAML notation for JSON objects in query params](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content).  Additional reasons to keep this behavior: less work in JS, and remains backward-compatible with wider array of generated clients (soft interop with OpenAPI 2.x).
cc @sanderpick @ipfs/wg-pinning-services
> docs: Pin.meta encoding in URL query param

- ipfs-pinning-service.yaml
This PR is doc-only change that clarifies that pinning services don't need to persist `Pin.origins` 
The rationale here is that 
- IPFS node can have many multiaddrs and storing them with every pin introduces unnecessary storage costs, as clients like `pin remote add` from go-ipfs  will put all mulltiaddrs of the local node
- Multiaddrs from `origins` are relevant only during the pinning operation, to speed up discovery of providers of mising blocks. 
- If user wants to persist "source peer"  they can add them to `meta` map instead
cc @obo20 (pinata) @whyrusleeping (estuary)
> docs: clarify Pin.origins persistence

- ipfs-pinning-service.yaml
Clarifies what is the implicit default – ambiguity pointed out by @alanshaw – thanks!
> docs: document default status filter

- .github/workflows/linter.yml
- .spectral.yaml
- Makefile
- ipfs-pinning-service.yaml
adds `operationId` properties to all routes. These can be used by code generators like `openapi-backend` to map routes to method names.
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. The operationId value is case-sensitive. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.
> – https://swagger.io/specification/#operation-object
> Handlers are registered for [operationIds](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-8) found in the OpenAPI definitions.
> – https://github.com/anttiviljami/openapi-backend#registering-handlers-for-operations
also fixes the linting warnings:
- adds …
> feat: add `operationId`s

- ipfs-pinning-service.yaml
This PR does not change the spec, it only updates `date-time` examples to use time-secfrac from [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6).
Improved precision is already supported by the spec,  but the lack of explicit example made some implementations  round things to a full second, causing issues like https://github.com/ipfs/kubo/issues/8762.
> docs: date-time example with time-secfrac

- README.md
- web3 storage is discontinuing support for the pinning API spec https://blog.web3.storage/posts/the-data-layer-is-here-with-the-new-web3-storage
- estuary is discontinued
- awaiting a reply from the nft.storage team about whether they continue to support the pinning API spec (https://filecoinproject.slack.com/archives/C021JJRH26B/p1704366048817589)
> fix: remove discontinued services
